spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

dgs:
  graphql:
    graphiql:
      enabled: true
    introspection:
      enabled: true
