spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/streamarr
    username: admin
    password: pass

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

dgs:
  graphql:
    graphiql:
      enabled: true
