type Query {
    me: Me!
    movie(id: ID!): Movie
    series(id: ID!): Series
    season(id: ID!): Season
    episode(id: ID!): Episode
    rating(id: ID!): Rating!
    library(id: ID!): Library!
    libraries: [Library!]!
    continueWatching(first: Int): [ContinueWatchingMedia!]!
    householdAdministration(householdId: ID!): HouseholdAdministration
    households(first: Int, after: String, last: Int, before: String): HouseholdAdministrationConnection!
    accountAdministration(accountId: ID!): AccountAdministration
    profileAdministration(profileId: ID!): ProfileAdministration
    accountInvitations(first: Int, after: String, last: Int, before: String): AccountInvitationConnection!
    profileSharePreview(profileId: ID!, householdId: ID!): ProfileSharePreview
    pendingShareOffers(householdId: ID!, first: Int, after: String, last: Int, before: String): ProfileShareConnection!
    profileShares(profileId: ID!, first: Int, after: String, last: Int, before: String): ProfileShareConnection!
    managerInvitations(profileId: ID!, first: Int, after: String, last: Int, before: String): ManagerInvitationConnection!
    pendingManagerInvitations(first: Int, after: String, last: Int, before: String): ManagerInvitationConnection!
    householdDevices(householdId: ID!, first: Int, after: String, last: Int, before: String): DeviceRegistrationConnection!
    esnBlocks(householdId: ID!, first: Int, after: String, last: Int, before: String): EsnBlockConnection!
    serverEsnBlocks(first: Int, after: String, last: Int, before: String): EsnBlockConnection!
    householdTeardownPreview(householdId: ID!): HouseholdTeardownPreview
    securityAuditEvents(first: Int, after: String, last: Int, before: String): SecurityAuditEventConnection!
    profileActivity(profileId: ID!, first: Int, after: String, last: Int, before: String): ProfileActivityConnection!
}
