package com.streamarr.server.domain.auth;

public enum CredentialKind {
  ACCOUNT_LOGIN,
  ACCOUNT_PASSWORD_VERIFICATION,
  PROFILE_PIN,
  ACCOUNT_INVITATION_CODE,
  PASSWORD_RESET_CODE,
  PROFILE_MANAGER_INVITATION_CODE,
  DEVICE_PAIRING_CODE
}
