package com.streamarr.server.domain.auth;

public enum SecurityAuditOperation {
  PROFILE_CREATED,
  PROFILE_RENAMED,
  PROFILE_POLICY_CHANGED,
  PROFILE_MANAGER_INVITED,
  PROFILE_MANAGER_ACCEPTED,
  PROFILE_MANAGER_INVITATION_REJECTED,
  PROFILE_MANAGER_INVITATION_CANCELED,
  PROFILE_MANAGER_RELINQUISHED,
  PROFILE_SHARE_OFFERED,
  PROFILE_SHARE_ACCEPTED,
  PROFILE_SHARE_REJECTED,
  PROFILE_SHARE_CANCELED,
  PROFILE_UNSHARED_BY_HOUSEHOLD,
  PROFILE_LEFT_HOME,
  PROFILE_DELETED,
  PROFILE_FORCE_DELETED,
  PROFILE_MANAGER_OVERRIDDEN,
  PROFILE_FORCE_UNSHARED,
  PROFILE_SELECTION_CLEARED,
  ACCOUNT_TRANSFERRED,
  HOUSEHOLD_OWNERSHIP_TRANSFERRED
}
