name: Build & Release Nightly

on:
  push:
    branches:
      - loom-test

jobs:
  build-nightly-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw spring-boot:build-image --batch-mode --no-transfer-progress org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage

      - name: Tag & publish to GitHub Container Registry
        run: |
          docker tag server:0.0.1-SNAPSHOT stuckya/streamarr-server:nightly
          docker push stuckya/streamarr-server:nightly
