name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-please-main
  cancel-in-progress: false

jobs:
  release:
    uses: streamarr/streamarr-workflows/.github/workflows/release-please.yml@768aa58c4d37fd4b049780b01adffdf38feb3b79
    secrets:
      app-client-id: ${{ secrets.ORG_STREAMARR_RELEASE_CLIENT_ID }}
      app-private-key: ${{ secrets.ORG_STREAMARR_RELEASE_PRIVATE_KEY }}
