name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-please-main
  cancel-in-progress: false

jobs:
  release:
    uses: streamarr/streamarr-workflows/.github/workflows/release-please.yml@4f248f00cffecd547583dc70a0abab492775eecf
    secrets:
      app-client-id: ${{ secrets.ORG_STREAMARR_RELEASE_CLIENT_ID }}
      app-private-key: ${{ secrets.ORG_STREAMARR_RELEASE_PRIVATE_KEY }}
