name: Test

on:
  push:
    branches:
      - loom-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=push
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set env
        run: echo "GITHUB_TITLE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title'] }}" >> $GITHUB_ENV


  test-2:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Test env
        run: echo GITHUB_TITLE

