#!/usr/bin/env python3
import json
import os
import sys
from pathlib import Path

path = Path(os.environ['FAKE_REGISTRY'])
state = json.loads(path.read_text())
args = sys.argv[1:]
if args[:3] == ['buildx', 'imagetools', 'create']:
    tag_index = args.index('--tag')
    tag = args[tag_index + 1]
    sources = args[tag_index + 2:]
    manifests = []
    for source in sources:
        manifests.extend(state['images'][source])
    state['images'][tag] = manifests
    reference = 'streamarr/streamarr-server@' + state['indexDigest']
    state['images'][reference] = manifests
    if '--metadata-file' in args:
        metadata = Path(args[args.index('--metadata-file') + 1])
        metadata.write_text(json.dumps({'containerimage.descriptor': {'digest': state['indexDigest']}}))
elif args[:4] == ['buildx', 'imagetools', 'inspect', '--raw']:
    print(json.dumps({'manifests': state.get('indexOverride', state['images'][args[-1]])}))
else:
    sys.exit(81)
path.write_text(json.dumps(state))
