#!/usr/bin/env python3
import os
import sys

if sys.argv[1:] != ['api', 'repos/streamarr/streamarr-server/git/ref/heads/main', '--jq', '.object.sha']:
    sys.exit(81)
if os.environ.get('FAKE_GITHUB_FAILURE') == 'true':
    sys.exit(1)
print(os.environ['FAKE_MAIN_REVISION'])
